services:
  ghost:
    image: ghost:${GHOST_VERSION}
    restart: always
    depends_on:
      - db
    ports:
      - "2368:2368"
    environment:
      url: ${url}
      database__client: ${database__client}
      database__connection__host: ${database__connection__host}
      database__connection__port: ${database__connection__port}
      database__connection__user: ${database__connection__user}
      database__connection__password: ${database__connection__password}
      database__connection__database: ${database__connection__database}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ghost-content:/var/lib/ghost/content

  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${database__connection__password}
      MYSQL_DATABASE: ${database__connection__database}
      MYSQL_USER: ${database__connection__user}
      MYSQL_PASSWORD: ${database__connection__password}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  ghost-content:
  db-data: