name: CI - Casper (CI-1)

on:
  push:
    branches: [develop, main]
    paths:
      - 'casper/**'
      - '.github/workflows/ci-casper.yml'
      - '.github/workflows/theme-ci.yml'
  pull_request:
    paths:
      - 'casper/**'
      - '.github/workflows/ci-casper.yml'
      - '.github/workflows/theme-ci.yml'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/theme-ci.yml
    with:
      theme: casper
