name: CI - Source (CI-2)

on:
  push:
    branches: [develop, main]
    paths:
      - 'source/**'
      - '.github/workflows/ci-source.yml'
      - '.github/workflows/theme-ci.yml'
  pull_request:
    paths:
      - 'source/**'
      - '.github/workflows/ci-source.yml'
      - '.github/workflows/theme-ci.yml'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/theme-ci.yml
    with:
      theme: source
