name: Validación de convención de commits

on:
  pull_request:
    branches: [develop, main]

permissions:
  contents: read

jobs:
  commitlint:
    name: Verificar Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      - name: Ejecutar commitlint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1